#!/usr/bin/env bash
#This bash script that creates a file and displays text
echo $$ > /var/run/myscript.pid

handle_sigterm() {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
exit 0
}

handle_sigint() {
	echo "Y U no love me?!"
}

handle_sigquit() {
	rm -f /var/run/myscript.pid
	exit 0
}

trap handle_sigterm SIGTERM
trap handle_sigint SIGINT
trap handle_sigquit SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
