#!/usr/bin/env bash
#This script lists the content of the current directory, displaying only the part of each filename after the first dash is displayed
for file in *; do
	if [[ -f "$file" && "$file" == *-* ]]; then
		echo "${file#*-}"
	fi
done
