#!/usr/bin/env bash
# This script configures an Ubuntu server
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker

# Backup /etc/hosts to ~/hosts.new
cp /etc/hosts ~/hosts.new

# Modify the ~/hosts.new file with sed
sed -i 's/localhost/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/facebook.com/8.8.8.8 facebook.com/' ~/hosts.new

# Overwrite the /etc/hosts file with the modified file
cp -f ~/hosts.new /etc/hosts
